# Refer: PEP 508, 517, 518 specifications.

# With PEP 517, the build is isolated and we cannot specify optional build
# dependencies. Thus we cannot use pyproject.toml

[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools", "wheel",
    "numpy", "cython",
    # Will only work when Mako supplies wheels / pip supports
    # installation from source
    # "mako",
    "jinja2", "transonic>=0.2.0"
]
