
channels:
  - conda-forge

dependencies:
  - python=3.7
  - pip:
    - pyfftw
    - numpy
    - cython
    - h5py
    - jupyter
    - matplotlib
    - pandas
    - sphinx
    - numpydoc
    - mako
    - sphinx_rtd_theme
    - hg+https://foss.heptapod.net/fluiddyn/fluiddyn#egg=fluiddyn
